### ISSUE TITLE
connectToSortable support (for multilist)

### ISSUE THREAD

**Issue by nickschot** [12StarsMedia/ember-ui-sortable#1]
Is there any specific reason why connectToSortable isn't implemented (yet)? Seems to be the only major feature missing. Would you accept a PR?

Related info: http://api.jqueryui.com/draggable/#option-connectToSortable

**Comment by ToddSmithSalter** [comment]
Hey Nick, I had no use case for implementing connectToSortable. If I understand correctly, this is an option of the draggable widget. Does anything need to be done here?

One other note, I've got an `ember-ui-draggable` component in progress, where connectToSortable would be defined.

**Comment by nickschot** [comment]
Sorry for the late reaction, it is indeed an option to make drag & drop possible between two lists. I don't think a lot of work is needed other than passing the argument to draggable.

My use case would be a list with items which can be dropped into another element composed of elements from the first list.

There's an example here: http://jqueryui.com/sortable/#connect-lists (do note that this example doesn't exactly behave as my use case as it removes the elements from the first list).

On another note, I'm not exactly sure anymore why I didn't mention connectWith (http://api.jqueryui.com/sortable/#option-connectWith), which seems to connect lists (instead of making a single element droppable on a list).

**Comment by ToddSmithSalter** [comment]
I see. So you have a clone action you need to employ?

Seems pretty straight forward to include. Do you feel up for a PR? If not, I'll make this a feature request and block some time to knock it out.

**Comment by nickschot** [comment]
Could sure try! Haven't really looked into the code yet, but got some time later this week :)

**Comment by nickschot** [comment]
I'm now actually implementing this in my app, so a PR might come soon if I get it working to my liking.

**Comment by nickschot** [comment]
Now that I look at it again, what I need is indeed an option of the draggable widget (I need an "immutable" source list from which items can be picked). 

Would you be ok with a draggable component being added to this addon? Or would you rather have me create a separate addon for that?

EDIT: as I need this anyway, I have already started working on a component. Progress is on https://github.com/nickschot/ember-ui-sortable/tree/draggable . A correct "receive" method is the most pressing thing left (apart from tests).

**Comment by ToddSmithSalter** [comment]
This has been addresses with #4 merge.
